apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-sonarqube
  namespace: sonarqube
  annotations:
    meta.helm.sh/release-name: sonarqube
    meta.helm.sh/release-namespace: sonarqube
  labels:
    app: sonarqube
    app.kubernetes.io/managed-by: Helm
    chart: sonarqube-10.5.1_2816
    heritage: Helm
    release: sonarqube
type: Opaque
data:
  jdbc-password: KjQ2dzZWezJKbmNXbHFyekV8UFRUOXhBYyhIRA==
