apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: lucky-eks-cluster-alb
  region: us-west-2
  version: "1.29"

nodeGroups:
  - name: lucky-eks-cluster
    instanceType: r5d.xlarge
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    volumeSize: 80
    volumeType: gp2
    volumeEncrypted: true
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
        fsx: true
        efs: true

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
    logRetentionInDays: 60

