apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eks-external-secret
  namespace: sonarqube
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: eks-secret-store
    kind: SecretStore
  target:
    name: eks-secret
  data:
  - secretKey: username
    remoteRef:
      key: rds!db-f5244589-c961-4fa7-b0e5-7459fd8d2929
      property: username
  - secretKey: password
    remoteRef:
      key: rds!db-f5244589-c961-4fa7-b0e5-7459fd8d2929
      property: password