apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eks-external-secret
  namespace: sonarqube
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: eks-secret-store
    kind: SecretStore
  target:
    name: eks-secret
  data:
  - secretKey: username
    remoteRef:
      key: lucky-rds-secrets
      property: username
  - secretKey: password
    remoteRef:
      key: lucky-rds-secrets
      property: password