apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarqube-secret
  namespace: sonarqube
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: sonarqube-secret-store
    kind: SecretStore
  target:
    name: sonarqube-secret
  data:
  - secretKey: SONAR_JDBC_USERNAME
    remoteRef:
      key: rds!db-64d0f348-5422-41bc-a7e2-eb15fd4c736e
      property: username
  - secretKey: SONAR_JDBC_PASSWORD
    remoteRef:
      key: rds!db-64d0f348-5422-41bc-a7e2-eb15fd4c736e
      property: password

