apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: sonarqube-secret-store
  namespace: sonarqube
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2
      auth:
        jwt:
          serviceAccountRef:
            name: sonarqube-sa
