apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: jenkins
    meta.helm.sh/release-namespace: jenkins
  creationTimestamp: "2024-05-04T12:04:46Z"
  generation: 3
  labels:
    app.kubernetes.io/component: jenkins-controller
    app.kubernetes.io/instance: jenkins
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jenkins
    helm.sh/chart: jenkins-5.1.8
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: jenkins
  namespace: jenkins
  resourceVersion: "1130716"
  uid: bb023626-e263-4c0c-bc01-f985d1eff0b0
spec:
  ingressClassName: nginx
  rules:
  - host: jenkins.siri.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jenkins
            port:
              number: 8080
  - host: sonar.siri.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sonarqube-sonarqube
            port:
              number: 9000
        