apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: application-ingress
  namespace: jenkins
  resourceVersion: "1130716"
  uid: bb023626-e263-4c0c-bc01-f985d1eff0b0
  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/use-default-backend: "true"
    nginx.ingress.kubernetes.io/default-backend: "custom-default-backend:80"
spec:
  ingressClassName: nginx
  rules:
  - host: application.siri.com
    http:
      paths:
      - path: /jenkins
        pathType: Prefix
        backend:
          service:
            name: jenkins
            port:
              number: 8080
      - path: /sonar
        pathType: Prefix
        backend:
          service:
            name: sonarqube-sonarqube
            port:
              number: 9000