---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: rds-secrets
  namespace: sonarqube
spec:
  provider: aws
  # secretObjects:
  # - secretName: rds-secret
  #   type: Opaque
  #   data: 
  #   - objectName: secret-token
  #     key: SECRET_TOKEN
  parameters:
    objects: |
      - objectName: rds!db-5cb3e94a-11de-4da6-8890-c3e35e7145b2
        objectType: secretsmanager
        jmesPath:
           - path: "username"
             objectAlias: "MySecretUsername"
           - path: "password"
             objectAlias: "jdbc-password"