apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jfrogdb-externalsecrets
  namespace: jfrog
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: jfrogdb-secretstore
    kind: SecretStore
  target:
    name: jfrog-secret
  data:
  - secretKey: POSTGRESQL_USERNAME
    remoteRef:
      key: rds!db-64d0f348-5422-41bc-a7e2-eb15fd4c736e
      property: username
  - secretKey: POSTGRESQL_PASSWORD
    remoteRef:
      key: rds!db-64d0f348-5422-41bc-a7e2-eb15fd4c736e
      property: password
