apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jfrogdb-externalsecrets
  namespace: jfrog
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: jfrogdb-secretstore
    kind: SecretStore
  target:
    name: jfrogdb-secrets
  data:
  - secretKey: PASSWORD
    remoteRef:
      key: rds!db-e6531643-8234-401b-8144-64263f2e1809
      property: password
