apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: application-cert
spec:
  secretName: application-tls-certs
  dnsNames:
  - sonarqube.siri.com
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer